"""Initial migration.

Generated by Django 4.0.4 on 2022-04-22 17:41.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("key", models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ("value", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
