# Generated by Django 4.0.4 on 2022-05-01 17:49

import autodonate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nickname', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', autodonate.models.TokenField(default=autodonate.models.TokenField.generate, max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('long_description', models.TextField(null=True)),
                ('group', models.CharField(max_length=32, null=True)),
                ('image', models.ImageField(null=True, upload_to='product/covers')),
                ('max_in_cart', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', autodonate.models.TokenField(default=autodonate.models.TokenField.generate, max_length=12, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodonate.player')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodonate.product')),
            ],
        ),
    ]
