# Generated by Django 4.0.2 on 2022-02-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodonate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodonate.paymentprocess', unique=True),
        ),
    ]
