"""Add ``project_name`` to ``Config`` table.

Generated by Django 4.0.4 on 2022-04-22 17:29.
"""

from django.db import migrations


def add_default_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    config = apps.get_model("autodonate", "Config")
    config.objects.create(
        key="project_name",
        value="MineServ",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("autodonate", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_values),
    ]
