# Generated by Django 4.0.2 on 2022-02-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodonate', '0002_alter_payment_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autodonate.paymentprocess'),
        ),
    ]
